### ISSUE TITLE
Graph for Open Phil by cause area and year only has one cause area

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/donations#121]
https://donations.vipulnaik.com/donor.php?donor=Open+Philanthropy+Project#donorDonationAmountsByCauseAreaAndYear

Right now both graphs in that section look like this:

![image](https://user-images.githubusercontent.com/1450515/57524710-e6d33c00-7328-11e9-8b12-4bd82522aecc.png)

The CSV looks like:

```
Year|Criminal justice reform|Total
2016|124400|124400
2017|1195500|1195500
Total|1319900|1319900
```

Possibly related to #74.

**Comment by vipulnaik** [comment]
I think this is due to the hash keys used for caching the charts being incorrect, as well as the fact that the pages aren't regenerated fully each time.

**Comment by vipulnaik** [comment]
ok, I think I figured this out.

The problem is that the key at https://github.com/vipulnaik/donations/blob/fa2d6f7ae35e8dd3c809590fb0aad6523bd12291/access-portal/backend/donorDoneeDonationAmountsByCauseAreaAndYear.inc#L112 is set using only the donor, rather than the donor/donee combination, so the key here matches the key for just the donor at https://github.com/vipulnaik/donations/blob/fa2d6f7ae35e8dd3c809590fb0aad6523bd12291/access-portal/backend/donorDonationAmountsByCauseAreaAndYear.inc#L145

So here's the sequence to reproduce:

1. Clear cache, images etc.
2. Visit https://donations.vipulnaik.com/donor.php?donor=Berkeley+Existential+Risk+Initiative -- this creates a HTML cache for the item and also records the PNG at https://donations.vipulnaik.com/images/a4f402dc814ab289674963475ad5d78a-timeseries.png
3. Visit https://donations.vipulnaik.com/donorDonee.php?donor=Berkeley+Existential+Risk+Initiative&donee=Machine+Intelligence+Research+Institute#donorDoneeDonationList -- this creates a HTML cache for this page and also updates the PNG at https://donations.vipulnaik.com/images/a4f402dc814ab289674963475ad5d78a-timeseries.png
4. Visit https://donations.vipulnaik.com/donor.php?donor=Berkeley+Existential+Risk+Initiative again -- now the HTML cache created in step 2 will be served, and will end up serving the PNG recorded in step 3, instead of the intended original recorded in step 2.

Note that step 2 is necessary to create the HTML cache, and step 3 is necessary to disrupt the PNG.
