### ISSUE TITLE
Improve the way we deal with renamings for donors and donees

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#128]
A few ideas:

- For both donors and donees, rename `former_name` to `other_names` and allow a pipe-separated list of possibilities.
- When a query is made using donor.php, donee.php, donorDonee.php, search both the main donor or donee column and the `other_names` column.

**Comment by riceissa** [comment]
Serving in multiple locations vs redirecting: I think I prefer redirecting, mainly so there's a canonical location, and to fit in with how existing sites like Wikipedia work. e.g. if someone goes to https://donations.vipulnaik.com/donor.php?donor=Open+Philanthropy+Project it should redirect to https://donations.vipulnaik.com/donor.php?donor=Open+Philanthropy rather than serving at the old location.

On the implementation:

* one way is to have an outer redirection layer that takes any incoming requests, checks whether this is an old name, then just sends the user to the new location. The advantage of this is that as far as the rest of the MySQL tables and PHP code are concerned, there is only a single name for each entity (i.e. none of the existing MySQL/PHP needs to be modified).
* another way is I think closer to what you are suggesting, where we go around modifying all the MySQL queries adding `... or other_names regexp $donor`.

What do you think?

**Comment by vipulnaik** [comment]
@riceissa I agree that redirecting is the better option. Thanks for explaining.

Outer redirection layer sounds good, if you have a clear idea of how to pull it off.

**Comment by riceissa** [comment]
Ok, I think this is working.

https://github.com/vipulnaik/donations/tree/better-renamings

You can try with e.g. `/donee.php?donee=Singularity Institute for Artificial Intelligence`

**Comment by vipulnaik** [comment]
I made a PR for easier review of changes, and have merged the PR. It's live now!
