### ISSUE TITLE
Rename "Open Philanthropy Project" -> "Open Philanthropy"

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#129]
~~Please do after #128!~~ #128 is done is this is ready to do.

- [x] Fix up donor metadata for Open Phil. Include `Open Phil` and `Open Philanthropy Project` as other names
- [x] Fix up all the donations from Open Phil
- [x] Also edit `affected_donors` and `publisher` for all docs where either of these values has `Open Philanthropy Project`

Can you also **document your steps (e.g., sed commands)** so that I can do similar renamings for other orgs?

**Comment by riceissa** [comment]
(this is a draft)

Documentation of steps (I ended up changing my mind about how to do things midway, so this documents the ideal way I should have started out with):

* In Vim, run `:args sql/**/*.sql`; this will load up all the SQL files. Then run `:argdo %s/\(['|]\)Open Philanthropy Project\(['|]\)/\1Open Philanthropy\2/ge | update`; this will search and replace across all SQL files. You will need to press space a bunch of times. Do `git diff` to review changes. (Optional: run `make reset && make read` to check that SQL files still insert correctly.) If things look good, then stage and commit.
* In the shell, run `grep -r 'Open Philanthropy Project' sql/ | wc -l`; this will give an estimate of approximately how many instances of the old name are left. I get 291.

* Back in Vim, run `:args sql/**/*.sql` to load SQL files again. Then run `:argdo %s/Open Philanthropy Project/Open Philanthropy/gce | update`. The difference this time is that we're looking for all instances of `Open Philanthropy Project` instead of just those that "stand on their own" in a field or occur as part of a pipe-separated list. Also we are passing the `c` flag to the replacement command so that we can verify each replacement before it happens. Press `y` to confirm a replacement or `n` to reject. The main thing to watch out for are document titles and inside quotes, where it's necessary to reject replacements. If you get tired at any point, Ctrl-c will abort the process while retaining any changes you've already made (you can then run the grep command above again to check how many more you have).

* FIXME: Still in Vim, this time I ran `:vim /\(the|The\) Open Philanthropy/ sql/**`. This is a special thing just for Open Phil though.

* Opened `sql/donors/private-foundations-and-subsidiaries.sql`. Since the "insert into" line at the top did not contain an `other_names` field, I added that. Then I went through all of the rows manually, inserting `NULL` for all of them except for the Open Phil row, where instead I entered `'Open Philanthropy Project|Open Phil'` for that column. At this point I staged this file and committed.

**Comment by riceissa** [comment]
This is now done!

**Comment by vipulnaik** [comment]
LGTM, thanks @riceissa! I've reimported the data on donations.vipulnaik.com now!
