### ISSUE TITLE
Import grants data for Public Welfare Foundation into Donations List Website

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#2]
Data is at http://www.publicwelfare.org/grants-process/our-grants/

Their site is currently giving 500 internal server errors, but you can look at the data in the Internet Archive: http://web.archive.org/web/20170701111713/http://www.publicwelfare.org/grants-process/our-grants/

**Comment by vipulnaik** [comment]
The site is back online, and the first link http://www.publicwelfare.org/grants-process/our-grants/ still works.

**Comment by riceissa** [comment]
This is basically done now at <https://github.com/riceissa/public-welfare-foundation>. The FIXMEs are parts I'm not sure about.

**Comment by vipulnaik** [comment]
FIXMEs have been fixed, and grants data has been inserted.

**Comment by vipulnaik** [comment]
It seems like they have a moving window of grants they show online, so you have to use Internet Archive snapshots to get old data, then patch/deduplicate it. We can get grants data for 2014, 2015, and 2016 this way.

**Comment by riceissa** [comment]
In the Internet Archive versions, I cannot click through the different pages. Most of the time when I click on a different page, it does nothing, and sometimes it says:

> Ups :( \
> Something went wrong

I think this happens because the data is being pulled from <http://www.publicwelfare.org/wp-admin/admin-ajax.php> but the source for that PHP page is no publicly visible, so the Internet Archive cannot fully replicate the interactive experience in its snapshots.

When I click on filter to filter to a single year, I am taken to a page that the Internet Archive has not archived (such as <http://www.publicwelfare.org:80/grants-process/our-grants/?years%5B%5D=2013>.

The upshot is that the only grants data for 2014, 2015, and 2016 we can get are the ones that appear on the front page of the snapshot.

**Comment by vipulnaik** [comment]
ok, closing for now :'(.
