### ISSUE TITLE
Import Knight Foundation grants data into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#45]
https://knightfoundation.org/grants

clicking on a grant gives information on the grant size etc. We need to pull all the information together for inserting into DLW.

**Comment by riceissa** [comment]
in progress at https://github.com/riceissa/knight-foundation

**Comment by riceissa** [comment]
Part of what I'm using for the `notes` column is the text in the "Goal" section of a grant. I'm getting `Data too long for column 'notes'` due to the following grant: https://knightfoundation.org/grants/6000

I wonder if I should try trimming that or if I should bump up the character limit on the `notes` column.

**Comment by riceissa** [comment]
Other than the above, I think this is basically done.

**Comment by vipulnaik** [comment]
Please trim that with an ellipsis if needed. We can't make columns too long and the notes column is already stretching its limits :).

**Comment by riceissa** [comment]
Done.

**Comment by vipulnaik** [comment]
So looking at a few examples, I think the Project Team field is what should go in as the donee, and the project name that currently goes in donee should go in donation_earmark.

Also, for Project team, please remove suffixes such as " inc." or "Inc" similar to the way we do it for Arnold Foundation and others where this problem arose.

**Comment by riceissa** [comment]
Done.
