### ISSUE TITLE
Import W. K. Kellogg Foundation grants into DLW

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#67]
https://www.wkkf.org/grants

**Comment by riceissa** [comment]
I have started on this at https://github.com/riceissa/kellogg-foundation

**Comment by riceissa** [comment]
This is done.

1. Since the raw data (32MB) and SQL file (9.1MB) are large, I didn't put them in the Git repo. Instead, they are in S3 under the donations directory (filename: `kellogg-2018-08-06.tar.bz2`).
2. There was at least one row with an `affected_states` value of 209, so I bumped the character limit for that and `affected_cities` up to 300. You will need to reload the schema before inserting.

**Comment by vipulnaik** [comment]
Inserted; needs cleanup/review.
