### ISSUE TITLE
Add new SQL table for donor-donee pairs

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/donations#70]
The goal of this table is to store manual information about the qualitative relationship between a specific donor and donee.

The contents of the table should be shown on donor-donee pages, such as https://donations.vipulnaik.com/donorDonee.php?donor=Open+Philanthropy+Project&donee=Machine+Intelligence+Research+Institute

**Comment by vipulnaik** [comment]
I'm discussing this with @riceissa over Facebook Messenger now and we will update the issue with more details based on our discussion.

**Comment by vipulnaik** [comment]
Plan for now: @riceissa will create a schema, then enter a few rows per the schema, then as he works on it, he might come up with ideas for more columns, realize some columns are useless, etc. He'll be in touch with me @vipulnaik for more discussion.

Suggested initial donor-donee pairs to try out:

- Open Philanthropy Project and Machine Intelligence Research Institute https://donations.vipulnaik.com/donorDonee.php?donor=Open+Philanthropy+Project&donee=Machine+Intelligence+Research+Institute
- Open Philanthropy Project and Center for Applied Rationality https://donations.vipulnaik.com/donorDonee.php?donor=Open+Philanthropy+Project&donee=Center+for+Applied+Rationality
- Open Philanthropy Project and The Humane League https://donations.vipulnaik.com/donorDonee.php?donor=Open+Philanthropy+Project&donee=The+Humane+League
- Effective Altruism Funds and Machine Intelligence Research Institute https://donations.vipulnaik.com/donorDonee.php?donor=Effective+Altruism+Funds&donee=Machine+Intelligence+Research+Institute

**Comment by riceissa** [comment]
The columns I've thought of so far:

- donor
- donee
- relationship start date (this seems useful to include, but might actually be hard to find as there is usually no specific moment when interactions between orgs begin, and might be better left to be computed somehow using the earliest donation date or earliest document about both orgs)
- relationship start date precision
- relationship end date and end date precision (might be good to include for symmetry, but this will probably be left blank almost always, since it's hard to distinguish between a relationship "ending" vs there just not being any recent interaction)
- key interaction example URLs (I think this is better to just get from the documents table and somehow specify in there which documents are more important)
- notes

It's somewhat tricky to come up with columns, because the main parts of the relationship are money flowing between the orgs (already covered in donations table), discussions referencing both orgs (already covered in documents table), and the people common to both orgs (already covered in Org Watch).

**Comment by riceissa** [comment]
There's also a lot of "fuzzy" things that are hard to record, like the similarities/differences in thinking styles/operation styles (e.g. level of transparency, opinions on how to deal with uncertainty), specific memes/intellectual traditions they have in common, direction/magnitude of influence (e.g. Holden's [admission](https://www.openphilanthropy.org/blog/three-key-issues-ive-changed-my-mind-about) that his worldviews have become more MIRI-esque).

**Comment by riceissa** [comment]
There might also be indirect relationships, e.g. maybe people at both organizations have taught at SPARC, or people from both orgs have previously worked at Google.

**Comment by vipulnaik** [comment]
@riceissa you can go ahead and add in the displaying of this information on donor-donee pages such as https://donations.vipulnaik.com/donorDonee.php?donor=Open+Philanthropy+Project&donee=The+Humane+League
